---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Add apache vhosts configuration.
  template: >
    src=vhost-ssl.conf.j2
    dest={{ nginx_conf_path }}/vhosts.conf
    owner=root group=root mode=644
  with_items: nginx_vhost_ssl
  notify: restart apache
  when: nginx_create_vhosts_ssl

- name: Add apache vhosts configuration.
  template: >
    src=vhosts.conf.j2
    dest={{ nginx_conf_path }}/vhosts.conf
    owner=root group=root mode=644
  with_items: nginx_vhost
  notify: restart apache
  when: nginx_create_vhosts_ssl